name = "Explore Modpack"
author = "Lowgain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95c33a81e16481b617ed09f388c7351b70f7e96b5b9769fedb5c56645109b256"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
