name = "Explore Modpack"
author = "Lowgain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46f43ec685620d32228cb91bdc313f3f9bdb9ad3a7bf01d86abe0df0e216c740"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
