name = "Explore Modpack"
author = "Lowgain"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75cdb09a798767b33328bd56da3a4f09d140244a0ecc3354543f6cd485e596f6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
