version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
lootr = true
comforts = true
tide = true
plushie_buddies = true
fleshz = true
monolib = true
creeperoverhaul = true
handcrafted = true
easymagic = true
extended_drawers = true
crittersandcompanions = true
easyanvils = true
ironchest = true
toms_storage = true
minecraft = true
animal_feeding_trough = true
disenchanting_table = true
